services:
  backend:
    image: ghcr.io/dilkihansapani/stock-management-system/backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - database
    networks:
      - stock_management_system-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
      restart_policy:
        condition: on-failure

  frontend:
    image: ghcr.io/dilkihansapani/stock-management-system/frontend:latest
    container_name: stock_management_system_frontend
    ports:
      - "3000:80"
    networks:
      - stock_management_system-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
      restart_policy:
        condition: on-failure

  database:
    image: ghcr.io/dilkihansapani/stock-management-system/database:latest
    container_name: stock_management_system-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - stock_management_system-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
      restart_policy:
        condition: on-failure

networks:
  stock_management_system-network:
    driver: bridge
