services:
  backend:
    build:
      context: ./backend/StockManagementSystem
      dockerfile: Dockerfile
    container_name: stock_management_system_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure

  frontend:
    build:
      context: ./frontend/stock_management_system_frontend
      dockerfile: Dockerfile
    container_name: stock_management_system_frontend
    ports:
      - "3000:80"
    restart: on-failure

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: stock_management_system-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
